### ISSUE TITLE
Storm looking for nodejs executable on my host machine

### ISSUE THREAD

**Issue by mdobson** [RallySoftware/node-storm#8]
Hi All!

I have a quick question on how to setup part of this module.

After submitting a nodejs topology to my cluster running on a VM I get this error. 

```
Sat, 30 Apr 2016 06:34:24 -04:00	172.17.0.4	6702	java.lang.RuntimeException: Error when launching multilang subprocess at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:66) at backtype.storm.spout.ShellSpout.open(ShellSpout.java:74) at backtype.storm.daemon.executor$fn__4654$fn__4669.invoke(executor.clj:522) at backtype.storm.util$async_loop$fn__458.invoke(util.clj:461) at clojure.lang.AFn.run(AFn.java:24) at java.lang.Thread.run(Thread.java:745) Caused by: java.io.IOException: Cannot run program "/Users/apigeelabs/.nvm/versions/node/v5.6.0/bin/node" (in directory "storm-local/supervisor/stormdist/index-1-1462012244/resources"): error=2, No such file or directory
```

I have node installed on the machines, and storm has access to it. How can I set the path to the node executable to be the proper one?

-Matt

**Comment by mdobson** [comment]
Found the issue! 

I use NVM to manage different nodejs installs on my base machine. This messes with the executable path submitted to the cluster. Running `nvm deactivate` will restore the path to a system installed nodejs, and the topology will be properly submitted. 

Is there an area of the code where overriding the node executable path that is submitted to the cluster with a topology possible? I'd gladly add a PR to make this configurable if pointed in the right direction.

-Matt
